title: Self Driving Cars
lang: en
description: SelfDrivingCars
repository: Weber-AGV/SelfDrivingCars
baseurl: /SelfDrivingCars

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

include:
  - _includes

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-tabs
